title: Page

pages: false

files:
	sortable: true
	fields:
		caption:
			label: Caption
			type: textarea

fields:
	title:
		label: Title
		type:  text
	about:
		label: About
		type:  wysiwyg
	info:
		label: Info
		type: wysiwyg