title: Site

sections:
	content:
	  type: fields
		fields:
			about:
				label: About
				type: editor

	pages:
		type: pages
		create:
			- default
			- home
			- bio
			- statement
			- gallery
			- events